name: catdogapp
description: A simple Flutter app to toggle between displaying 'Cat' and 'Dog' text with respective icons.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  bloc: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.3

flutter:
  uses-material-design: true